security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_database:
            entity:
                class: App\Entity\Personne
                property : login
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER,ROLE_EMPLOYE, ROLE_RESP]
        ROLE_RESP: [ROLE_USER]
        ROLE_EMPLOYE: [ROLE_USER]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: /logout
                target: /

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                check_path: login
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/qcm, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_USER }

    encoders:
        App\Entity\Personne :
            algorithm: bcrypt
            cost: 12
