#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /
    controller: App\Controller\HomeController::index

qcm:
    path: /qcm
    controller: App\Controller\QcmController::index
show:
    path: /qcm/{slug}-{id}
    controller: App\Controller\QcmController::show
    requirements: 
        slug : '[a-z0-9\-]*'
response:
    path: /qcm/repondre/{slug}-{id}
    controller: App\Controller\QcmController::response
    requirements:
        slug: '[a-z0-9\-]*'
submit:
    path: /qcm/submit/{slug}-{id}
    controller: App\Controller\QcmController::submit
    requirements:
        slug: '[a-z0-9\-]*'
index: 
    path: /admin
    controller: App\Controller\Admin\AdminQcmController::index
create:
    path: /admin/create
    controller: App\Controller\Admin\AdminQcmController::new         
edit:
    path: /admin/{id}
    controller: App\Controller\Admin\AdminQcmController::edit
    methods: GET|POST
delete:
    path: /admin/{id}
    controller: App\Controller\Admin\AdminQcmController::delete
    methods: DELETE
login:
    path: /login
    controller : App\Controller\SecurityController::login
register:
    path: /register
    controller : App\Controller\SecurityController::register
logout:
    path: /logout


