#index:
#    path: /
#    controller: App\Controller\DefaultController::index


home:
    path: /
    controller: App\Controller\HomeController::index

qcm:
    path: /qcm
    controller: App\Controller\QcmController::index    